packages:
  - apps/*
  - '!apps/web'
  - libs/*
  - libs/**/*
  - plugins/*

catalog:
  '@angular/animations': 20.3.4
  '@angular/cdk': 20.2.9
  '@angular/common': 20.3.4
  '@angular/compiler': 20.3.4
  '@angular/core': 20.3.4
  '@angular/forms': 20.3.4
  '@angular/material': 20.2.9
  '@angular/platform-browser': 20.3.4
  '@angular/platform-browser-dynamic': 20.3.4
  '@angular/router': 20.3.4
  '@anthropic-ai/sdk': 0.65.0
  '@esbuild-plugins/node-modules-polyfill': 0.2.2
  '@google/generative-ai': 0.24.1
  '@inquirer/prompts': 7.9.0
  '@modelcontextprotocol/sdk': 1.23.1
  '@vscode/ripgrep': 1.15.9
  axios: 1.12.2
  chalk: 5.6.2
  date-fns: 4.1.0
  dompurify: 3.3.1
  express: 5.1.0
  glob: 11.1.0
  marked: 16.4.0
  oauth4webapi: 3.8.3
  openai: 6.16.0
  os: 0.1.2
  path: 0.12.7
  pdf2json: 4.0.0
  rxjs: 7.8.2
  sharp: 0.34.4
  tslib: 2.8.1
  turndown: 7.2.2
  yaml: 2.8.1
  yargs: 18.0.0
  zone.js: 0.15.1

catalogs:
  dev:
    '@angular-devkit/core': 20.3.5
    '@angular-devkit/schematics': 20.3.5
    '@angular/build': 20.3.5
    '@angular/cli': 20.3.5
    '@angular/compiler-cli': 20.3.4
    '@angular/language-service': 20.3.4
    '@commitlint/cli': 20.1.0
    '@commitlint/config-conventional': 20.0.0
    '@esbuild-plugins/node-globals-polyfill': 0.2.3
    '@eslint/eslintrc': 3.3.1
    '@eslint/js': 9.37.0
    '@img/sharp-darwin-arm64': 0.34.4
    '@jest/globals': 30.2.0
    '@nx/angular': 22.2.3
    '@nx/devkit': 22.2.3
    '@nx/esbuild': 22.2.3
    '@nx/eslint': 22.2.3
    '@nx/eslint-plugin': 22.2.3
    '@nx/jest': 22.2.3
    '@nx/js': 22.2.3
    '@nx/node': 22.2.3
    '@nx/playwright': 22.2.3
    '@nx/web': 22.2.3
    '@nx/workspace': 22.2.3
    '@playwright/test': 1.56.0
    '@schematics/angular': 20.3.5
    '@swc-node/register': 1.11.1
    '@swc/cli': 0.7.8
    '@swc/core': 1.13.19
    '@swc/helpers': 0.5.17
    '@trivago/prettier-plugin-sort-imports': 5.2.2
    '@types/express': 5.0.3
    '@types/http-proxy-middleware': 1.0.0
    '@types/jest': 30.0.0
    '@types/node': 24.7.2
    '@types/dompurify': 3.0.5
    '@types/turndown': 5.0.6
    '@types/yargs': 17.0.35
    '@typescript-eslint/eslint-plugin': ^8.46.3
    '@typescript-eslint/parser': ^8.46.3
    '@typescript-eslint/utils': 8.46.1
    angular-eslint: 20.4.0
    electron: 38.3.0
    electron-builder: 26.0.12
    esbuild: 0.25.10
    eslint: 9.37.0
    eslint-config-prettier: 10.1.8
    eslint-plugin-import: 2.32.0
    eslint-plugin-playwright: 2.2.2
    eslint-plugin-prefer-arrow: 1.2.3
    eslint-plugin-prettier: 5.5.4
    http-proxy-middleware: 3.0.5
    husky: 9.1.7
    jest: 30.2.0
    jest-environment-jsdom: 30.2.0
    jest-environment-node: 30.2.0
    jest-preset-angular: 15.0.2
    jsdom: 27.0.0
    json-sort-cli: 4.0.21
    jsonc-eslint-parser: 2.4.1
    lint-staged: 16.2.4
    nodemon: 3.1.10
    nx: 22.2.3
    opn-cli: 5.0.0
    prettier: 3.6.2
    swc-loader: 0.2.6
    ts-jest: 29.4.5
    ts-loader: 9.5.4
    ts-node: 10.9.2
    tsx: 4.20.6
    typescript: 5.9.3
    typescript-eslint: 8.46.1

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - electron-winstaller
  - lmdb
  - msgpackr-extract
  - unrs-resolver

onlyBuiltDependencies:
  - '@swc/core'
  - '@vscode/ripgrep'
  - electron
  - esbuild
  - nx
  - sharp
