ignoredBuiltDependencies:
  - '@parcel/watcher'
  - electron-winstaller
  - lmdb
  - msgpackr-extract
  - unrs-resolver

onlyBuiltDependencies:
  - '@swc/core'
  - '@vscode/ripgrep'
  - electron
  - esbuild
  - nx
  - sharp
