/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AddMessageRequest {
  content: string
  answerToEventId?: string
  sessionContext?: { [key: string]: any }
}
