/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AgentConfig {
  id?: string
  namespaceId: string
  name: string
  description?: string
  instructions?: string
  modelName?: string
}
