/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AgentConfig {
  advancedExecution?: boolean
  createdBy?: string
  createdOn?: string
  description?: string
  enabled?: boolean
  externalMetadata?: { [key: string]: any }
  id?: string
  instructions?: string
  integrations?: { [key: string]: Array<string> }
  modelName?: string
  name: string
  namespaceId?: string
  subAgents?: Array<string>
  updatedBy?: string
  updatedOn?: string
}
