/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityMetadata } from './entity-metadata'

export interface AgentFinishedEvent {
  namespaceId: string
  caseId: string
  type: 'AgentFinishedEvent'
  timestamp: string
  metadata: EntityMetadata
  id: string
  agentId: string
  agentName: string
  llmProvider?: string
  llmModel?: string
}
