/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgentDefinitionToolSummary } from './agent-definition-tool-summary'

export interface AgentDefinition {
  agentConfigId: string
  name: string
  instructions?: string
  resolvedModelApiName: string
  resolvedProviderName: string
  tools: Array<AgentDefinitionToolSummary>
  advancedExecution: boolean
  namespaceId: string
  userId?: string
}
