/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiProvider } from './ai-provider'

export interface AiProviderPage {
  content: Array<AiProvider>
  page: number
  size: number
  totalElements: number
  totalPages: number
}
