/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AiProvider {
  id?: string
  namespaceId?: string | null
  userId?: string | null
  name: string
  description?: string
  apiType: AiProviderApiTypeEnum
  baseUrl?: string
  apiKey?: string
}
export enum AiProviderApiTypeEnum {
  OpenAI = 'OpenAI',
  Anthropic = 'Anthropic',
  Gemini = 'Gemini',
}
