/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityMetadata } from './entity-metadata'
import { Actor } from './actor'

export interface AnswerEvent {
  namespaceId: string
  caseId: string
  type: 'AnswerEvent'
  timestamp: string
  metadata: EntityMetadata
  id: string
  questionId: string
  actor: Actor
  answer: string
}
