/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AuthSetting {
  id?: string
  namespaceId?: string | null
  userId?: string | null
  name: string
  description?: string
  authType: AuthSettingAuthTypeEnum
  data?: { [key: string]: string }
}
export enum AuthSettingAuthTypeEnum {
  OAUTH_DISCOVERABLE = 'OAUTH_DISCOVERABLE',
  OAUTH_REGISTERED = 'OAUTH_REGISTERED',
  OAUTH_CUSTOM = 'OAUTH_CUSTOM',
  API_KEY = 'API_KEY',
  BEARER_TOKEN = 'BEARER_TOKEN',
  BASIC_AUTH = 'BASIC_AUTH',
}
