/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface BasicAuthAuthSetting {
  userId?: string | null
  namespaceId?: string | null
  authType: 'BasicAuthAuthSetting'
  description?: string
  name: string
  id?: string
  username?: string
  password?: string
}
