/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface BearerTokenAuthSetting {
  authType: 'BearerTokenAuthSetting'
  userId?: string | null
  namespaceId?: string | null
  description?: string
  name: string
  id?: string
  token?: string
}
