/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Case {
  created?: string
  favorite: boolean
  id?: string
  lastMessageAt?: string
  modified?: string
  namespaceId: string
  parentCaseId?: string
  removed: boolean
  /**
   * The caller\'s direct relation on this case
   */
  role?: CaseRoleEnum
  scheduledPromptId?: string
  status: CaseStatusEnum
  title?: string
}
export enum CaseRoleEnum {
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}
export enum CaseStatusEnum {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  IDLE = 'IDLE',
  KILLED = 'KILLED',
  ERROR = 'ERROR',
}
