/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgentRunningEvent } from './agent-running-event'
import { ConfirmationResolvedEvent } from './confirmation-resolved-event'
import { AgentFinishedEvent } from './agent-finished-event'
import { AgentSelectedEvent } from './agent-selected-event'
import { IntentionGeneratedEvent } from './intention-generated-event'
import { ThinkingEvent } from './thinking-event'
import { MessageEvent } from './message-event'
import { WarnEvent } from './warn-event'
import { TextChunkEvent } from './text-chunk-event'
import { PendingConfirmationEvent } from './pending-confirmation-event'
import { ToolResponseEvent } from './tool-response-event'
import { QuestionEvent } from './question-event'
import { ToolSelectedEvent } from './tool-selected-event'
import { AnswerEvent } from './answer-event'
import { ErrorEvent } from './error-event'
import { CaseStatusEvent } from './case-status-event'
import { ToolRequestEvent } from './tool-request-event'

export type CaseEvent =
  | AgentFinishedEvent
  | AgentRunningEvent
  | AgentSelectedEvent
  | AnswerEvent
  | CaseStatusEvent
  | ConfirmationResolvedEvent
  | ErrorEvent
  | IntentionGeneratedEvent
  | MessageEvent
  | PendingConfirmationEvent
  | QuestionEvent
  | TextChunkEvent
  | ThinkingEvent
  | ToolRequestEvent
  | ToolResponseEvent
  | ToolSelectedEvent
  | WarnEvent
