/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Case {
  id?: string
  namespaceId: string
  status: CaseStatusEnum
  title?: string
  parentCaseId?: string
  created?: string
  removed: boolean
}
export enum CaseStatusEnum {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  IDLE = 'IDLE',
  KILLED = 'KILLED',
  ERROR = 'ERROR',
}
