/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Case {
  created?: string
  favorite: boolean
  id?: string
  lastMessageAt?: string
  modified?: string
  namespaceId: string
  parentCaseId?: string
  /**
   * Timestamp of the caller\'s last read. Null = never read (unread).
   */
  readAt?: string
  removed: boolean
  /**
   * The caller\'s direct relation on this case
   */
  role?: CaseRoleEnum
  /**
   * Per-case override of the run cost threshold, in the platform currency unit. Null means inherit from the namespace or platform default (never \"no limit\" or \"zero\"). Set upfront for costly runs, or written by the enforcement mechanism on continuation.
   */
  runCostThreshold?: number
  scheduledPromptId?: string
  status: CaseStatusEnum
  title?: string
}
export enum CaseRoleEnum {
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}
export enum CaseStatusEnum {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  IDLE = 'IDLE',
  KILLED = 'KILLED',
  ERROR = 'ERROR',
}
