/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitWorkspaceSummary } from './git-workspace-summary'

export interface CaseWorkspaceView {
  branchName?: string
  cleanupReason?: string
  equipped: boolean
  failureReason?: string
  git?: GitWorkspaceSummary
  recoveryRequired: boolean
  rootCaseId?: string
  status?: string
}
