/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CaseUserListItem {
  email: string
  externalId: string
  firstname?: string
  id: string
  lastname?: string
  /**
   * The user\'s direct role on this case.
   */
  role: CaseUserListItemRoleEnum
}
export enum CaseUserListItemRoleEnum {
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}
