/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityMetadata } from './entity-metadata'

export interface ConfirmationResolvedEvent {
  namespaceId: string
  caseId: string
  type: 'ConfirmationResolvedEvent'
  timestamp: string
  metadata: EntityMetadata
  id: string
  pendingEventId: string
  confirmed: boolean
  resultText: string
}
