/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EnrichmentPhaseTrace {
  phaseIndex: number
  prompt: string
  llmOutput: string
  enrichmentContent?: string
  success: boolean
}
