/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Result of an exchange file deletion.
 */
export interface ExchangeDeleteResponse {
  /**
   * Whether the deletion succeeded.
   */
  success: boolean
  /**
   * Human-readable outcome message.
   */
  message: string
}
