/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Metadata for a single file in an exchange scope.
 */
export interface ExchangeFileEntry {
  /**
   * Opaque entity tag derived from size and last-modified time.
   */
  etag?: string
  /**
   * File name (last path segment).
   */
  filename: string
  /**
   * Last modification timestamp.
   */
  lastModified: string
  /**
   * Detected MIME type, or null if it could not be determined.
   */
  mimeType?: string
  /**
   * Path of the file relative to its exchange root, using forward slashes.
   */
  path: string
  /**
   * Scope the file belongs to.
   */
  scope: ExchangeFileEntryScopeEnum
  /**
   * File size in bytes.
   */
  size: number
}
export enum ExchangeFileEntryScopeEnum {
  CASE = 'CASE',
  NAMESPACE = 'NAMESPACE',
}
