/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExchangeGitChanges } from './exchange-git-changes'
import { GitWorkspaceSummary } from './git-workspace-summary'

export interface ExchangeEnvironment {
  branch?: string
  changes?: ExchangeGitChanges
  equipped: boolean
  error?: string
  git?: GitWorkspaceSummary
  path?: string
  status?: string
}
