/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Feedback {
  id: string
  namespaceId: string
  caseId: string
  caseEventId: string
  positive: boolean
  type?: string
  comment?: string
  createdBy?: string
  createdOn: string
  updatedBy?: string
  updatedOn: string
}
