/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FeedbackInput {
  caseEventId: string
  /**
   * Optional free-text note. Ignored (cleared) when positive=true.
   */
  comment?: string
  positive: boolean
  /**
   * Optional category label. Ignored (cleared) when positive=true.
   */
  type?: string
}
