/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface GitWorkspaceSummary {
  branchState: string
  dirty?: boolean
  error?: string
  headSha?: string
  observedAt?: string
  prHeadSha?: string
  prNumber?: number
  prState: string
  prUrl?: string
  remoteSha?: string
  unpushedCommits?: number
}
