/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface GitWorkspaceSummary {
  /**
   * Where the workspace branch stands against the remote
   */
  branchState: GitWorkspaceSummaryBranchStateEnum
  /**
   * Whether the worktree has local changes, untracked files included. Null when it could not be read
   */
  dirty?: boolean
  /**
   * Why the observation failed. Null when it succeeded. Never a secret
   */
  error?: string
  /**
   * Commit checked out in the workspace. Null when it could not be read
   */
  headSha?: string
  /**
   * When this observation started
   */
  observedAt?: string
  /**
   * Head commit of the pull request. Null without one
   */
  prHeadSha?: string
  /**
   * Number of the pull request. Null without one
   */
  prNumber?: number
  /**
   * The pull request of the workspace branch. UNKNOWN never means that there is none
   */
  prState: GitWorkspaceSummaryPrStateEnum
  /**
   * Web address of the pull request. Null without one
   */
  prUrl?: string
  /**
   * Commit of the remote branch. Null when the branch is not on the remote
   */
  remoteSha?: string
  /**
   * Commits of the workspace branch missing from the remote. Null unless the branch is on the remote
   */
  unpushedCommits?: number
}
export enum GitWorkspaceSummaryBranchStateEnum {
  DETACHED = 'DETACHED',
  LOCAL_ONLY = 'LOCAL_ONLY',
  PUSHED = 'PUSHED',
  UNPUSHED_COMMITS = 'UNPUSHED_COMMITS',
  UNKNOWN = 'UNKNOWN',
}
export enum GitWorkspaceSummaryPrStateEnum {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  MERGED = 'MERGED',
  CLOSED_UNMERGED = 'CLOSED_UNMERGED',
  NONE = 'NONE',
  UNKNOWN = 'UNKNOWN',
}
