/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface IntegrationTypeDescriptor {
  /**
   * True for built-in integrations enabled by adding their type directly to an agent's
   * integrations map (no IntegrationConfig instance) — surfaced as a simple toggle in the
   * agent form. False for regular, instance-backed integration types.
   */
  builtIn?: boolean
  configSchema?: any | null
  description: string
  displayName: string
  type: string
}
