/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface IntegrationConfig {
  authSettingName?: string
  description?: string
  id?: string
  integrationType: string
  name: string
  namespaceId?: string | null
  parameters?: any | null
  userId?: string | null
}
