/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntegrationConfigToolPreviewTool } from './integration-config-tool-preview-tool'

/**
 * Tools an IntegrationConfig yields for the calling user, resolved from the stored row as is (the user-level overlay merge applied by an agent run is NOT applied) and without any agent allowlist. Nothing is persisted.
 */
export interface IntegrationConfigToolPreview {
  /**
   * Name of the previewed config, also the prefix of every tool name.
   */
  configName: string
  /**
   * Why the plugin could not build its tool set (`ExceptionClass: message`), or null when `tools` is the result. A `TimeoutException` means the preview stopped waiting after the configured timeout (agentos.integrations.preview-provide-tools-timeout-ms); a `RejectedExecutionException` means every preview worker was busy and the plugin was not called.
   */
  error?: string
  /**
   * Integration type of the previewed config (plugin key).
   */
  integrationType: string
  /**
   * The plugin\'s describeNamespace line for this config, or null when the plugin gives none, fails or does not answer within the configured timeout (agentos.integrations.preview-describe-namespace-timeout-ms).
   */
  namespaceDescription?: string
  /**
   * Tools the plugin built for this config; empty when `error` is set.
   */
  tools: Array<IntegrationConfigToolPreviewTool>
}
