/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface IntegrationTypeDescriptor {
  type: string
  displayName: string
  description: string
  configSchema?: any | null
  /**
   * When true, this integration type is built-in (no config instance required).
   * Manually added: the backend exposes this field but the OpenAPI spec is not yet updated.
   */
  builtIn?: boolean
}
