/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityMetadata } from './entity-metadata'

export interface IntegrationConfig {
  metadata: EntityMetadata
  namespaceId: string
  name: string
  integrationType: string
  parameters?: any | null
  id: string
}
