/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface IntegrationConfig {
  /**
   * When true, this configuration is granted to every agent within its scope without the agent having to name it in its integrations map. Only allowed on types whose descriptor reports autoGrantable.
   */
  autoGrant?: boolean
  authSettingName?: string
  description?: string
  id?: string
  integrationType: string
  name: string
  namespaceId?: string | null
  parameters?: any | null
  userId?: string | null
}
