/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface LlmModelConfig {
  id?: string
  llmConfigId: string
  namespaceId?: string
  userId?: string
  apiName: string
  alias?: string
  priority: number
  temperature?: number
  maxTokens?: number
}
