/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Namespace {
  id?: string
  name: string
  description?: string
  /**
   * Optional filesystem path to a directory containing base configuration for this namespace (agents, tools, etc.)
   */
  configPath?: string
}
