/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface NamespaceListItem {
  id: string
  name: string
  description?: string
  configPath?: string
  externalId?: string
  defaultAgentName?: string
  /**
   * The caller\'s effective role on this namespace.
   */
  role: NamespaceListItemRoleEnum
}
export enum NamespaceListItemRoleEnum {
  SUPER_ADMIN = 'SUPER-ADMIN',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}
