/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface NamespaceUserListItem {
  id: string
  externalId: string
  email: string
  firstname?: string
  lastname?: string
  /**
   * The user\'s direct role on this namespace
   */
  role: NamespaceUserListItemRoleEnum
}
export enum NamespaceUserListItemRoleEnum {
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}
