/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface OAuthRegisteredAuthSetting {
  authType: 'OAuthRegisteredAuthSetting'
  description?: string
  id?: string
  name: string
  namespaceId?: string | null
  userId?: string | null
  authorizationUrl?: string
  clientId?: string
  clientSecret?: string
  scopes?: string
  tokenUrl?: string
}
