/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface OAuthDiscoverableAuthSetting {
  authType: 'OAuthDiscoverableAuthSetting'
  description?: string
  id?: string
  name: string
  namespaceId?: string | null
  userId?: string | null
  clientId?: string
  clientSecret?: string
  discoveryUrl?: string
  scopes?: string
}
