/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityMetadata } from './entity-metadata'

export interface PendingConfirmationEvent {
  caseId: string
  id: string
  metadata: EntityMetadata
  namespaceId: string
  timestamp: string
  type: 'PendingConfirmationEvent'
  analysisInstructions: string
  inputJson: string
  toolName: string
  toolRequestId: string
}
