/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PromptTranslateRequest {
  /**
   * Namespace external ID for AI model resolution (resolved server-side). Mutually exclusive with namespaceId; at least one is required.
   */
  namespaceExternalId?: string
  /**
   * Namespace UUID for AI model resolution. Mutually exclusive with namespaceExternalId; at least one is required.
   */
  namespaceId?: string
}
