/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PromptEffectiveRequest {
  namespaceId: string
  userId: string
  agentConfigId?: string | null
}
