/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PromptTranslateRequest {
  /**
   * Namespace external ID for AI model resolution (resolved server-side). Required only for platform-scoped prompts. Mutually exclusive with namespaceId.
   */
  namespaceExternalId?: string
  /**
   * Namespace UUID for AI model resolution. Required only for platform-scoped prompts. Mutually exclusive with namespaceExternalId.
   */
  namespaceId?: string
}
