/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PromptParameter } from './prompt-parameter'

export interface Prompt {
  agentConfigId?: string | null
  content: Array<string>
  createdBy?: string
  createdOn?: string
  description?: string
  externalMetadata?: { [key: string]: any }
  id?: string
  name: string
  namespaceId?: string | null
  parameters: Array<PromptParameter>
  updatedBy?: string
  updatedOn?: string
  userId?: string | null
}
