/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityMetadata } from './entity-metadata'

export interface QuestionEvent {
  caseId: string
  id: string
  metadata: EntityMetadata
  namespaceId: string
  timestamp: string
  type: 'QuestionEvent'
  agentId: string
  agentName: string
  options?: Array<string>
  question: string
}
