/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Recurrence } from './recurrence'
import { Planning } from './planning'

export interface ScheduledPrompt {
  agentConfigId: string
  createdBy?: string
  createdOn?: string
  description?: string
  enabled: boolean
  id?: string
  lastRunAt?: string
  name: string
  namespaceId?: string | null
  nextRunAt?: string
  planning: Planning
  promptContent: string
  recurrence: Recurrence
  updatedBy?: string
  updatedOn?: string
  userId?: string | null
}
