/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NamespaceRoleEntry } from './namespace-role-entry'

export interface SyncUserRolesRequest {
  namespaceRoles: Array<NamespaceRoleEntry>
  userExternalId: string
}
