/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityMetadata } from './entity-metadata'

export interface TextChunkEvent {
  type: 'TextChunkEvent'
  timestamp: string
  caseId: string
  projectId: string
  id: string
  metadata: EntityMetadata
  chunk: string
}
