/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityMetadata } from './entity-metadata'

export interface ToolSelectedEvent {
  namespaceId: string
  caseId: string
  type: 'ToolSelectedEvent'
  timestamp: string
  metadata: EntityMetadata
  id: string
  agentId: string
  toolName: string
}
