/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityMetadata } from './entity-metadata'
import { EnrichmentPhaseTrace } from './enrichment-phase-trace'

export interface ToolRequestEvent {
  namespaceId: string
  caseId: string
  type: 'ToolRequestEvent'
  timestamp: string
  metadata: EntityMetadata
  id: string
  toolRequestId: string
  toolName: string
  args?: string
  enrichmentPhases?: Array<EnrichmentPhaseTrace>
}
