/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UsageRecord {
  agentConfigId?: string
  agentName: string
  apiModelName?: string
  cacheReadTokens: number
  cacheWriteTokens: number
  caseId: string
  cost?: number | null
  createdOn: string
  id: string
  inputTokens: number
  namespaceId: string
  outcome: string
  outputTokens: number
  providerName?: string
  source: string
  timestamp: string
  totalTokens: number
  userId?: string
}
