/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserAiProvider } from './user-ai-provider'

export interface UserAiProviderPage {
  content: Array<UserAiProvider>
  page: number
  size: number
  totalElements: number
  totalPages: number
}
