/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserGroupCreateRequest {
  /**
   * Subset of userExternalIdsToAdd who should receive the ADMIN role; each must also be a member.
   */
  adminExternalIds: Set<string>
  agentIds: Set<string>
  name: string
  namespaceId: string
  userExternalIdsToAdd: Set<string>
}
