/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserIntegrationConfig {
  id?: string
  namespaceId?: string
  userId?: string
  name: string
  integrationType: string
  description?: string
  parameters?: any | null
}
