/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserGroupMember {
  email?: string
  /**
   * Identity-provider key used to add or remove this member
   */
  externalId: string
  firstname?: string
  lastname?: string
  /**
   * The user\'s relation to the group
   */
  role: UserGroupMemberRoleEnum
  userId: string
}
export enum UserGroupMemberRoleEnum {
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}
