/**
 * AgentOS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserMembershipRole {
  /**
   * Target role for this user on the entity. Null means revoke all relations.
   */
  role?: UserMembershipRoleRoleEnum
  /**
   * Internal user id.
   */
  userId: string
}
export enum UserMembershipRoleRoleEnum {
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}
