package io.whozoss.agentos.a2a.dto

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonValue

/**
 * A2A Task state (spec §4.1.3).
 *
 * Prototype mapping from AgentOS [io.whozoss.agentos.sdk.caseFlow.CaseStatus]:
 * - PENDING (case not yet started) → `submitted`
 * - RUNNING (agent turn in flight) → `working`
 * - IDLE   (turn ended, awaiting user) → `input-required`   ← v1 heuristic
 * - KILLED → `canceled`
 * - ERROR  → `failed`
 *
 * See [io.whozoss.agentos.a2a.mapping.CaseStatusMapper] for the actual mapping code
 * and its limitations documented in `docs/a2a.md`.
 */
enum class A2ATaskState(
    @JsonValue val value: String,
) {
    SUBMITTED("submitted"),
    WORKING("working"),
    INPUT_REQUIRED("input-required"),
    COMPLETED("completed"),
    CANCELED("canceled"),
    FAILED("failed"),
    REJECTED("rejected"),
    AUTH_REQUIRED("auth-required"),
    UNKNOWN("unknown"),
    ;

    fun isTerminal(): Boolean = this == COMPLETED || this == CANCELED || this == FAILED || this == REJECTED
}

/**
 * A2A `TaskStatus` (spec §4.1.2).
 */
@JsonIgnoreProperties(ignoreUnknown = true)
data class A2ATaskStatus(
    val state: A2ATaskState,
    @JsonInclude(JsonInclude.Include.NON_NULL)
    val message: A2AMessage? = null,
    /** ISO-8601 timestamp. */
    val timestamp: String,
)

/**
 * A2A `Artifact` (spec §4.1.7) — an output generated by the agent.
 *
 * Prototype: not populated. AgentOS surfaces agent output as chat messages
 * (`MessageEvent` with `role=AGENT`), so we emit them as `TaskArtifactUpdateEvent`s
 * with a synthetic single-part artifact. See TODO in docs/a2a.md.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
data class A2AArtifact(
    val artifactId: String,
    val parts: List<A2APart>,
    @JsonInclude(JsonInclude.Include.NON_NULL) val name: String? = null,
    @JsonInclude(JsonInclude.Include.NON_NULL) val description: String? = null,
    @JsonInclude(JsonInclude.Include.NON_NULL) val extensions: List<String>? = null,
    @JsonInclude(JsonInclude.Include.NON_NULL) val metadata: Map<String, Any?>? = null,
)

/**
 * A2A `Task` (spec §4.1.1) — the fundamental unit of work.
 * Maps 1:1 to an AgentOS [io.whozoss.agentos.caseFlow.Case].
 */
@JsonIgnoreProperties(ignoreUnknown = true)
data class A2ATask(
    val id: String,
    val contextId: String,
    val status: A2ATaskStatus,
    val kind: String = "task",
    @JsonInclude(JsonInclude.Include.NON_NULL)
    val history: List<A2AMessage>? = null,
    @JsonInclude(JsonInclude.Include.NON_NULL)
    val artifacts: List<A2AArtifact>? = null,
    @JsonInclude(JsonInclude.Include.NON_NULL)
    val metadata: Map<String, Any?>? = null,
)

// -----------------------------------------------------------------------------
// Streaming events (spec §4.2)
// -----------------------------------------------------------------------------

/**
 * A2A `TaskStatusUpdateEvent` (spec §4.2.1).
 */
@JsonIgnoreProperties(ignoreUnknown = true)
data class TaskStatusUpdateEvent(
    val taskId: String,
    val contextId: String,
    val status: A2ATaskStatus,
    val final: Boolean = false,
    val kind: String = "status-update",
    @JsonInclude(JsonInclude.Include.NON_NULL)
    val metadata: Map<String, Any?>? = null,
)

/**
 * A2A `TaskArtifactUpdateEvent` (spec §4.2.2).
 */
@JsonIgnoreProperties(ignoreUnknown = true)
data class TaskArtifactUpdateEvent(
    val taskId: String,
    val contextId: String,
    val artifact: A2AArtifact,
    val append: Boolean = false,
    val lastChunk: Boolean = true,
    val kind: String = "artifact-update",
    @JsonInclude(JsonInclude.Include.NON_NULL)
    val metadata: Map<String, Any?>? = null,
)
