package io.whozoss.agentos.agent

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.collections.shouldHaveAtLeastSize
import io.kotest.matchers.shouldBe
import io.kotest.matchers.shouldNotBe
import io.kotest.matchers.string.shouldContain
import io.mockk.every
import io.mockk.mockk
import io.mockk.slot
import io.whozoss.agentos.sdk.actor.Actor
import io.whozoss.agentos.sdk.actor.ActorRole
import io.whozoss.agentos.sdk.aiProvider.AiModel
import io.whozoss.agentos.sdk.caseEvent.AgentFinishedEvent
import io.whozoss.agentos.sdk.caseEvent.MessageContent
import io.whozoss.agentos.sdk.caseEvent.MessageEvent
import io.whozoss.agentos.sdk.caseEvent.ToolRequestEvent
import io.whozoss.agentos.sdk.caseEvent.ToolResponseEvent
import io.whozoss.agentos.sdk.entity.EntityMetadata
import io.whozoss.agentos.sdk.tool.StandardTool
import kotlinx.coroutines.flow.toList
import org.springframework.ai.chat.client.ChatClient
import org.springframework.ai.chat.prompt.Prompt
import org.springframework.ai.tool.ToolCallback
import java.util.UUID

/**
 * Tests for the ToolCallback registration fix.
 *
 * Root cause: AgentSimple previously used MethodToolCallback, which generated the
 * LLM-facing JSON schema by reflecting on the wrapper method signature
 * `invoke(jsonArgs: String?)`. This produced a schema with a single `jsonArgs`
 * property instead of the tool's real parameters (e.g. `timezone`), causing the
 * LLM to always send empty arguments.
 *
 * Fix: AgentSimple now implements ToolCallback directly using DefaultToolDefinition,
 * passing the tool's own inputSchema verbatim to the LLM without any reflection override.
 *
 * ## Call strategy
 *
 * When tools are registered AgentSimple uses call() (blocking) rather than stream().
 * Spring AI's stream() processes parallel tool calls one at a time, causing the LLM
 * to loop indefinitely. call() batches all callbacks from one turn and sends one
 * follow-up request.
 *
 * These tests therefore stub call() for tool-present scenarios and stream().content()
 * for tool-absent (history replay) scenarios.
 */
class AgentSimpleToolCallbackTest :
    StringSpec({
        timeout = 5000

        fun makeAgent(
            agentId: UUID,
            chatClient: ChatClient,
            tools: Collection<StandardTool<*>>,
        ): AgentSimple {
            val model =
                AiModel(
                    metadata = EntityMetadata(id = agentId),
                    name = "TestAgent",
                    description = "Test agent",
                    modelName = "claude-opus",
                    providerName = "anthropic",
                )
            return AgentSimple(
                metadata = EntityMetadata(id = agentId),
                model = model,
                chatClient = chatClient,
                tools = tools,
            )
        }

        fun userMessage(
            namespaceId: UUID,
            caseId: UUID,
            text: String,
        ) = MessageEvent(
            namespaceId = namespaceId,
            caseId = caseId,
            actor = Actor("user-1", "user", ActorRole.USER),
            content = listOf(MessageContent.Text(text)),
        )

        // -------------------------------------------------------------------------
        // Schema registration
        // -------------------------------------------------------------------------

        "createToolCallbackWithEvents should expose the tool inputSchema verbatim" {
            // The LLM-facing ToolDefinition must use the schema declared in StandardTool,
            // not a schema generated by reflecting on the wrapper method signature.
            val namespaceId = UUID.randomUUID()
            val caseId = UUID.randomUUID()
            val agentId = UUID.randomUUID()

            val expectedSchema =
                """
                {
                    "type": "object",
                    "properties": {
                        "timezone": {
                            "type": "string",
                            "description": "IANA timezone identifier"
                        }
                    },
                    "required": ["timezone"]
                }
                """.trimIndent()

            val fakeTool =
                object : StandardTool<Nothing> {
                    override val name = "GetCurrentDateTime"
                    override val description = "Get the current date and time in a timezone"
                    override val inputSchema = expectedSchema
                    override val version = "1.0.0"
                    override val paramType: Class<Nothing>? = null

                    override fun execute(input: Nothing?): String = ""
                }

            // Tools present — AgentSimple uses call(), not stream()
            val capturedCallbacks = slot<List<ToolCallback>>()
            val mockChatClient = mockk<ChatClient>(relaxed = true)
            val mockCallSpec = mockk<ChatClient.CallResponseSpec>(relaxed = true)
            every {
                mockChatClient.prompt(any<Prompt>()).toolCallbacks(capture(capturedCallbacks)).call()
            } returns mockCallSpec
            every { mockCallSpec.content() } returns "done"

            val agent = makeAgent(agentId, mockChatClient, listOf(fakeTool))
            agent.run(listOf(userMessage(namespaceId, caseId, "test"))).toList()

            // The callback registered with Spring AI must carry the tool's own schema
            val registeredCallback =
                capturedCallbacks.captured.firstOrNull { it.toolDefinition.name() == "GetCurrentDateTime" }
            registeredCallback shouldNotBe null
            registeredCallback!!.toolDefinition.inputSchema() shouldBe expectedSchema
            registeredCallback.toolDefinition.description() shouldContain "timezone"
        }

        // -------------------------------------------------------------------------
        // Argument forwarding
        // -------------------------------------------------------------------------

        "tool call args from LLM are forwarded to executeWithJson and recorded in ToolRequestEvent" {
            // Regression: MethodToolCallback schema mismatch caused LLM to send empty args.
            // Now that the schema is correct, the LLM sends e.g. {"timezone":"America/New_York"}.
            // This test verifies those args reach the tool and the event.
            val namespaceId = UUID.randomUUID()
            val caseId = UUID.randomUUID()
            val agentId = UUID.randomUUID()

            val receivedArgs = mutableListOf<String?>()
            val fakeTool =
                object : StandardTool<Nothing> {
                    override val name = "GetCurrentDateTime"
                    override val description = "Get the current date and time"
                    override val inputSchema =
                        """{"type":"object","properties":{"timezone":{"type":"string"}},"required":["timezone"]}"""
                    override val version = "1.0.0"
                    override val paramType: Class<Nothing>? = null

                    override fun execute(input: Nothing?): String = ""

                    override fun executeWithJson(json: String?): String {
                        receivedArgs += json
                        return """{"success":true,"datetime":"2026-02-27T11:02:37-05:00","timezone":"America/New_York"}"""
                    }
                }

            // Tools present — AgentSimple uses call().
            // Simulate Spring AI executing the callback synchronously inside call().
            val mockChatClient = mockk<ChatClient>(relaxed = true)
            val mockCallSpec = mockk<ChatClient.CallResponseSpec>(relaxed = true)
            val toolCallbackSlot = slot<List<ToolCallback>>()
            every { mockChatClient.prompt(any<Prompt>()).toolCallbacks(capture(toolCallbackSlot)).call() } answers {
                val cb = toolCallbackSlot.captured.first { it.toolDefinition.name() == "GetCurrentDateTime" }
                cb.call("""{"timezone":"America/New_York"}""")
                mockCallSpec
            }
            every { mockCallSpec.content() } returns "It is 11:02 AM EST"

            val agent = makeAgent(agentId, mockChatClient, listOf(fakeTool))
            val events = agent.run(listOf(userMessage(namespaceId, caseId, "what time is it in New York?"))).toList()

            // Tool received the args
            receivedArgs.all { it?.contains("America/New_York") == true } shouldBe true

            // ToolRequestEvent recorded the exact args
            val toolRequest = events.filterIsInstance<ToolRequestEvent>().firstOrNull()
            toolRequest shouldNotBe null
            toolRequest!!.args shouldContain "America/New_York"

            // ToolResponseEvent recorded the result
            val toolResponse = events.filterIsInstance<ToolResponseEvent>().firstOrNull()
            toolResponse shouldNotBe null
            (toolResponse!!.output as MessageContent.Text).content shouldContain "America/New_York"
        }

        // -------------------------------------------------------------------------
        // History replay safety (empty-args crash fix)
        // -------------------------------------------------------------------------

        "convertEventsToMessages should not crash when history contains a ToolRequestEvent with blank args" {
            // Regression: Spring AI's AnthropicChatModel calls ModelOptionsUtils.jsonToMap()
            // on tool call arguments when rebuilding conversation history.
            // An empty string ("") is not valid JSON and throws MismatchedInputException.
            // The fix normalises null/blank args to "{}" before creating AssistantMessage.ToolCall.
            //
            // No tools registered — AgentSimple uses stream().content() in this path.
            val namespaceId = UUID.randomUUID()
            val caseId = UUID.randomUUID()
            val agentId = UUID.randomUUID()

            val mockChatClient = mockk<ChatClient>(relaxed = true)
            stubChatResponseStream(mockChatClient, "follow-up response")

            val agent = makeAgent(agentId, mockChatClient, emptyList())

            // History that includes a prior tool call with empty args (as stored before the fix)
            val historyWithEmptyArgs =
                listOf(
                    userMessage(namespaceId, caseId, "what time is it in New York?"),
                    io.whozoss.agentos.sdk.caseEvent.ToolRequestEvent(
                        namespaceId = namespaceId,
                        caseId = caseId,
                        toolRequestId = "prior-request-id",
                        toolName = "GetCurrentDateTime",
                        args = "", // empty — would crash AnthropicChatModel before the fix
                    ),
                    io.whozoss.agentos.sdk.caseEvent.ToolResponseEvent(
                        namespaceId = namespaceId,
                        caseId = caseId,
                        toolRequestId = "prior-request-id",
                        toolName = "GetCurrentDateTime",
                        output = MessageContent.Text("{\"success\":true,\"datetime\":\"2026-02-27T16:00:00Z\"}"),
                        success = true,
                    ),
                    MessageEvent(
                        namespaceId = namespaceId,
                        caseId = caseId,
                        actor = Actor(agentId.toString(), "TestAgent", ActorRole.AGENT),
                        content = listOf(MessageContent.Text("It is 11:00 AM EST")),
                    ),
                    userMessage(namespaceId, caseId, "and what about Paris?"),
                )

            // Must not throw — before the fix this crashed with MismatchedInputException
            val events = agent.run(historyWithEmptyArgs).toList()

            events shouldHaveAtLeastSize 3
            events.filterIsInstance<AgentFinishedEvent>().firstOrNull() shouldNotBe null
        }

        "convertEventsToMessages should not crash when history contains a ToolRequestEvent with null args" {
            // No tools registered — AgentSimple uses stream().content() in this path.
            val namespaceId = UUID.randomUUID()
            val caseId = UUID.randomUUID()
            val agentId = UUID.randomUUID()

            val mockChatClient = mockk<ChatClient>(relaxed = true)
            stubChatResponseStream(mockChatClient, "response")

            val agent = makeAgent(agentId, mockChatClient, emptyList())

            val historyWithNullArgs =
                listOf(
                    userMessage(namespaceId, caseId, "what time is it?"),
                    io.whozoss.agentos.sdk.caseEvent.ToolRequestEvent(
                        namespaceId = namespaceId,
                        caseId = caseId,
                        toolRequestId = "prior-request-id",
                        toolName = "GetCurrentDateTime",
                        args = null, // null — also unsafe before the fix
                    ),
                    io.whozoss.agentos.sdk.caseEvent.ToolResponseEvent(
                        namespaceId = namespaceId,
                        caseId = caseId,
                        toolRequestId = "prior-request-id",
                        toolName = "GetCurrentDateTime",
                        output = MessageContent.Text("{\"success\":true}"),
                        success = true,
                    ),
                    MessageEvent(
                        namespaceId = namespaceId,
                        caseId = caseId,
                        actor = Actor(agentId.toString(), "TestAgent", ActorRole.AGENT),
                        content = listOf(MessageContent.Text("It is 4 PM")),
                    ),
                    userMessage(namespaceId, caseId, "follow-up"),
                )

            val events = agent.run(historyWithNullArgs).toList()

            events shouldHaveAtLeastSize 3
            events.filterIsInstance<AgentFinishedEvent>().firstOrNull() shouldNotBe null
        }
    })
