package io.whozoss.factory.planchange.persistence

import org.springframework.data.neo4j.core.schema.Id
import org.springframework.data.neo4j.core.schema.Node
import java.time.Instant

/**
 * Spring Data Neo4j projection of one append-only plan-change decision event
 * (Phase 8 governed replanning).
 *
 * Modelled on
 * [io.whozoss.factory.agentattempt.persistence.DurableAgentAttemptJournalNode]:
 * the node [id] is the composite business key
 * `(organizationId, workstreamId, namespaceId, workflowId, proposalId, sequence)`
 * encoded as a single string (see [compositeId]); [sequence] is the monotone
 * ordering key generated by the adapter as `MAX(sequence) + 1`.
 *
 * Decision events are never updated nor deleted: they are the durable decision
 * history of the proposal, the source of truth of the proposal's derived
 * `currentStatus` cache. [idempotencyKey] makes `/decide` replays answerable
 * without appending a duplicate event.
 */
@Node("PlanChangeDecision")
data class PlanChangeDecisionNode(
    @Id
    val id: String,
    val organizationId: String,
    val workstreamId: String,
    val namespaceId: String,
    val workflowId: String,
    val proposalId: String,
    val sequence: Long,
    val status: String,
    val actorId: String,
    val reason: String? = null,
    val idempotencyKey: String? = null,
    val recordedAt: Instant,
) {
    companion object {
        /** Encodes the composite business key into a single node id. */
        fun compositeId(
            organizationId: String,
            workstreamId: String,
            namespaceId: String,
            workflowId: String,
            proposalId: String,
            sequence: Long,
        ): String = "$organizationId|$workstreamId|$namespaceId|$workflowId|$proposalId|$sequence"
    }
}
