/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AgentFinishedEvent } from '../../models/agent-finished-event';
import { AgentRunningEvent } from '../../models/agent-running-event';
import { AgentSelectedEvent } from '../../models/agent-selected-event';
import { AnswerEvent } from '../../models/answer-event';
import { CaseStatusEvent } from '../../models/case-status-event';
import { IntentionGeneratedEvent } from '../../models/intention-generated-event';
import { MessageEvent } from '../../models/message-event';
import { QuestionEvent } from '../../models/question-event';
import { TextChunkEvent } from '../../models/text-chunk-event';
import { ThinkingEvent } from '../../models/thinking-event';
import { ToolRequestEvent } from '../../models/tool-request-event';
import { ToolResponseEvent } from '../../models/tool-response-event';
import { ToolSelectedEvent } from '../../models/tool-selected-event';
import { WarnEvent } from '../../models/warn-event';

export interface Update2$Params {
  id: string;
  body:
    | AgentFinishedEvent
    | AgentRunningEvent
    | AgentSelectedEvent
    | AnswerEvent
    | CaseStatusEvent
    | IntentionGeneratedEvent
    | MessageEvent
    | QuestionEvent
    | TextChunkEvent
    | ThinkingEvent
    | ToolRequestEvent
    | ToolResponseEvent
    | ToolSelectedEvent
    | WarnEvent;
}

export function update2(
  http: HttpClient,
  rootUrl: string,
  params: Update2$Params,
  context?: HttpContext
): Observable<
  StrictHttpResponse<
    | AgentFinishedEvent
    | AgentRunningEvent
    | AgentSelectedEvent
    | AnswerEvent
    | CaseStatusEvent
    | IntentionGeneratedEvent
    | MessageEvent
    | QuestionEvent
    | TextChunkEvent
    | ThinkingEvent
    | ToolRequestEvent
    | ToolResponseEvent
    | ToolSelectedEvent
    | WarnEvent
  >
> {
  const rb = new RequestBuilder(rootUrl, update2.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<
        | AgentFinishedEvent
        | AgentRunningEvent
        | AgentSelectedEvent
        | AnswerEvent
        | CaseStatusEvent
        | IntentionGeneratedEvent
        | MessageEvent
        | QuestionEvent
        | TextChunkEvent
        | ThinkingEvent
        | ToolRequestEvent
        | ToolResponseEvent
        | ToolSelectedEvent
        | WarnEvent
      >;
    })
  );
}

update2.PATH = '/api/case-events/{id}';
