package io.whozoss.factory.agentattempt.persistence

import io.whozoss.factory.agentattempt.domain.AgentAttemptStatus
import io.whozoss.factory.agentattempt.domain.DurableAgentAttemptJournalEntry
import org.springframework.data.neo4j.core.schema.Id
import org.springframework.data.neo4j.core.schema.Node
import java.time.Instant

/**
 * Spring Data Neo4j projection of one append-only attempt-transition journal
 * entry (Lot C durable-execution, Phase 2 durable unit).
 *
 * Modelled on [io.whozoss.factory.delivery.persistence.DeliveryRecordNode]:
 * the node [id] is the composite business key
 * `(organizationId, workstreamId, namespaceId, workflowId, stepId, attemptId,
 * sequence)` encoded as a single string (see [compositeId]); [sequence] is the
 * monotone ordering key generated by the adapter as `MAX(sequence) + 1`.
 *
 * Entries are never updated nor deleted: the mutable
 * [DurableAgentAttemptNode] stays the authoritative CURRENT state, this journal
 * is its durable transition history.
 */
@Node("DurableAgentAttemptJournal")
data class DurableAgentAttemptJournalNode(
    @Id
    val id: String,
    val organizationId: String,
    val workstreamId: String,
    val namespaceId: String,
    val workflowId: String,
    val stepId: String,
    val attemptId: String,
    val sequence: Long,
    /** `null` only for the initial registration entry. */
    val fromStatus: String? = null,
    val toStatus: String,
    val ownerToken: String? = null,
    val failureCode: String? = null,
    val resultEvidenceId: String? = null,
    val lastObservedEventId: String? = null,
    val revisionAfter: Int,
    val recordedAt: Instant,
) {
    fun toDomain(): DurableAgentAttemptJournalEntry = DurableAgentAttemptJournalEntry(
        attemptId = attemptId,
        sequence = sequence,
        fromStatus = fromStatus?.let { AgentAttemptStatus.fromDbValue(it) },
        toStatus = AgentAttemptStatus.fromDbValue(toStatus),
        ownerToken = ownerToken,
        failureCode = failureCode,
        resultEvidenceId = resultEvidenceId,
        lastObservedEventId = lastObservedEventId,
        revisionAfter = revisionAfter,
        recordedAt = recordedAt,
    )

    companion object {
        fun compositeId(
            organizationId: String,
            workstreamId: String,
            namespaceId: String,
            workflowId: String,
            stepId: String,
            attemptId: String,
            sequence: Long,
        ): String = "$organizationId|$workstreamId|$namespaceId|$workflowId|$stepId|$attemptId|$sequence"
    }
}
