/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AgentFinishedEvent } from '../models/agent-finished-event';
import { AgentRunningEvent } from '../models/agent-running-event';
import { AgentSelectedEvent } from '../models/agent-selected-event';
import { AnswerEvent } from '../models/answer-event';
import { CaseStatusEvent } from '../models/case-status-event';
import { create2 } from '../fn/case-event-rest-controller/create-2';
import { Create2$Params } from '../fn/case-event-rest-controller/create-2';
import { delete2 } from '../fn/case-event-rest-controller/delete-2';
import { Delete2$Params } from '../fn/case-event-rest-controller/delete-2';
import { getById2 } from '../fn/case-event-rest-controller/get-by-id-2';
import { GetById2$Params } from '../fn/case-event-rest-controller/get-by-id-2';
import { getByIds2 } from '../fn/case-event-rest-controller/get-by-ids-2';
import { GetByIds2$Params } from '../fn/case-event-rest-controller/get-by-ids-2';
import { IntentionGeneratedEvent } from '../models/intention-generated-event';
import { listByParent2 } from '../fn/case-event-rest-controller/list-by-parent-2';
import { ListByParent2$Params } from '../fn/case-event-rest-controller/list-by-parent-2';
import { MessageEvent } from '../models/message-event';
import { QuestionEvent } from '../models/question-event';
import { TextChunkEvent } from '../models/text-chunk-event';
import { ThinkingEvent } from '../models/thinking-event';
import { ToolRequestEvent } from '../models/tool-request-event';
import { ToolResponseEvent } from '../models/tool-response-event';
import { ToolSelectedEvent } from '../models/tool-selected-event';
import { update2 } from '../fn/case-event-rest-controller/update-2';
import { Update2$Params } from '../fn/case-event-rest-controller/update-2';
import { WarnEvent } from '../models/warn-event';

@Injectable({ providedIn: 'root' })
export class CaseEventRestControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getById2()` */
  static readonly GetById2Path = '/api/case-events/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById2()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById2$Response(params: GetById2$Params, context?: HttpContext): Observable<StrictHttpResponse<(AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent)>> {
    const obs = getById2(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById2(params: GetById2$Params, context?: HttpContext): Observable<(AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent)> {
    const resp = this.getById2$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<(AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent)>): (AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent) => r.body)
    );
  }

  /** Path part for operation `update2()` */
  static readonly Update2Path = '/api/case-events/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update2()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update2$Response(params: Update2$Params, context?: HttpContext): Observable<StrictHttpResponse<(AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent)>> {
    const obs = update2(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update2$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update2(params: Update2$Params, context?: HttpContext): Observable<(AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent)> {
    const resp = this.update2$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<(AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent)>): (AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent) => r.body)
    );
  }

  /** Path part for operation `delete2()` */
  static readonly Delete2Path = '/api/case-events/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete2()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete2$Response(params: Delete2$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = delete2(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete2(params: Delete2$Params, context?: HttpContext): Observable<void> {
    const resp = this.delete2$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `create2()` */
  static readonly Create2Path = '/api/case-events';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create2()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create2$Response(params: Create2$Params, context?: HttpContext): Observable<StrictHttpResponse<(AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent)>> {
    const obs = create2(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create2$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create2(params: Create2$Params, context?: HttpContext): Observable<(AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent)> {
    const resp = this.create2$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<(AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent)>): (AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent) => r.body)
    );
  }

  /** Path part for operation `getByIds2()` */
  static readonly GetByIds2Path = '/api/case-events/by-ids';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getByIds2()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getByIds2$Response(params: GetByIds2$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<(AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent)>>> {
    const obs = getByIds2(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getByIds2$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getByIds2(params: GetByIds2$Params, context?: HttpContext): Observable<Array<(AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent)>> {
    const resp = this.getByIds2$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<(AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent)>>): Array<(AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent)> => r.body)
    );
  }

  /** Path part for operation `listByParent2()` */
  static readonly ListByParent2Path = '/api/case-events/by-parentId/{parentId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listByParent2()` instead.
   *
   * This method doesn't expect any request body.
   */
  listByParent2$Response(params: ListByParent2$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<(AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent)>>> {
    const obs = listByParent2(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listByParent2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listByParent2(params: ListByParent2$Params, context?: HttpContext): Observable<Array<(AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent)>> {
    const resp = this.listByParent2$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<(AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent)>>): Array<(AgentFinishedEvent | AgentRunningEvent | AgentSelectedEvent | AnswerEvent | CaseStatusEvent | IntentionGeneratedEvent | MessageEvent | QuestionEvent | TextChunkEvent | ThinkingEvent | ToolRequestEvent | ToolResponseEvent | ToolSelectedEvent | WarnEvent)> => r.body)
    );
  }

}
