/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { debugAllPlugins } from '../fn/plugin-controller/debug-all-plugins';
import { DebugAllPlugins$Params } from '../fn/plugin-controller/debug-all-plugins';
import { debugPlugin } from '../fn/plugin-controller/debug-plugin';
import { DebugPlugin$Params } from '../fn/plugin-controller/debug-plugin';
import { getAllPlugins } from '../fn/plugin-controller/get-all-plugins';
import { GetAllPlugins$Params } from '../fn/plugin-controller/get-all-plugins';
import { getPlugin } from '../fn/plugin-controller/get-plugin';
import { GetPlugin$Params } from '../fn/plugin-controller/get-plugin';
import { PluginActionResponse } from '../models/plugin-action-response';
import { PluginInfo } from '../models/plugin-info';
import { PluginUploadResponse } from '../models/plugin-upload-response';
import { reloadAllAgents } from '../fn/plugin-controller/reload-all-agents';
import { ReloadAllAgents$Params } from '../fn/plugin-controller/reload-all-agents';
import { reloadPlugin } from '../fn/plugin-controller/reload-plugin';
import { ReloadPlugin$Params } from '../fn/plugin-controller/reload-plugin';
import { startPlugin } from '../fn/plugin-controller/start-plugin';
import { StartPlugin$Params } from '../fn/plugin-controller/start-plugin';
import { stopPlugin } from '../fn/plugin-controller/stop-plugin';
import { StopPlugin$Params } from '../fn/plugin-controller/stop-plugin';
import { unloadPlugin } from '../fn/plugin-controller/unload-plugin';
import { UnloadPlugin$Params } from '../fn/plugin-controller/unload-plugin';
import { uploadPlugin } from '../fn/plugin-controller/upload-plugin';
import { UploadPlugin$Params } from '../fn/plugin-controller/upload-plugin';

@Injectable({ providedIn: 'root' })
export class PluginControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `stopPlugin()` */
  static readonly StopPluginPath = '/api/plugins/{pluginId}/stop';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `stopPlugin()` instead.
   *
   * This method doesn't expect any request body.
   */
  stopPlugin$Response(
    params: StopPlugin$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<PluginActionResponse>> {
    const obs = stopPlugin(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `stopPlugin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  stopPlugin(params: StopPlugin$Params, context?: HttpContext): Observable<PluginActionResponse> {
    const resp = this.stopPlugin$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<PluginActionResponse>): PluginActionResponse => r.body));
  }

  /** Path part for operation `startPlugin()` */
  static readonly StartPluginPath = '/api/plugins/{pluginId}/start';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `startPlugin()` instead.
   *
   * This method doesn't expect any request body.
   */
  startPlugin$Response(
    params: StartPlugin$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<PluginActionResponse>> {
    const obs = startPlugin(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `startPlugin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  startPlugin(params: StartPlugin$Params, context?: HttpContext): Observable<PluginActionResponse> {
    const resp = this.startPlugin$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<PluginActionResponse>): PluginActionResponse => r.body));
  }

  /** Path part for operation `reloadPlugin()` */
  static readonly ReloadPluginPath = '/api/plugins/{pluginId}/reload';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reloadPlugin()` instead.
   *
   * This method doesn't expect any request body.
   */
  reloadPlugin$Response(
    params: ReloadPlugin$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<PluginActionResponse>> {
    const obs = reloadPlugin(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reloadPlugin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reloadPlugin(params: ReloadPlugin$Params, context?: HttpContext): Observable<PluginActionResponse> {
    const resp = this.reloadPlugin$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<PluginActionResponse>): PluginActionResponse => r.body));
  }

  /** Path part for operation `uploadPlugin()` */
  static readonly UploadPluginPath = '/api/plugins/upload';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadPlugin()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadPlugin$Response(
    params?: UploadPlugin$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<PluginUploadResponse>> {
    const obs = uploadPlugin(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadPlugin$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadPlugin(params?: UploadPlugin$Params, context?: HttpContext): Observable<PluginUploadResponse> {
    const resp = this.uploadPlugin$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<PluginUploadResponse>): PluginUploadResponse => r.body));
  }

  /** Path part for operation `reloadAllAgents()` */
  static readonly ReloadAllAgentsPath = '/api/plugins/reload-agents';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reloadAllAgents()` instead.
   *
   * This method doesn't expect any request body.
   */
  reloadAllAgents$Response(
    params?: ReloadAllAgents$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<PluginActionResponse>> {
    const obs = reloadAllAgents(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reloadAllAgents$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reloadAllAgents(params?: ReloadAllAgents$Params, context?: HttpContext): Observable<PluginActionResponse> {
    const resp = this.reloadAllAgents$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<PluginActionResponse>): PluginActionResponse => r.body));
  }

  /** Path part for operation `getAllPlugins()` */
  static readonly GetAllPluginsPath = '/api/plugins';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllPlugins()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPlugins$Response(
    params?: GetAllPlugins$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<Array<PluginInfo>>> {
    const obs = getAllPlugins(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllPlugins$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPlugins(params?: GetAllPlugins$Params, context?: HttpContext): Observable<Array<PluginInfo>> {
    const resp = this.getAllPlugins$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<Array<PluginInfo>>): Array<PluginInfo> => r.body));
  }

  /** Path part for operation `getPlugin()` */
  static readonly GetPluginPath = '/api/plugins/{pluginId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPlugin()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPlugin$Response(params: GetPlugin$Params, context?: HttpContext): Observable<StrictHttpResponse<PluginInfo>> {
    const obs = getPlugin(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPlugin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPlugin(params: GetPlugin$Params, context?: HttpContext): Observable<PluginInfo> {
    const resp = this.getPlugin$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<PluginInfo>): PluginInfo => r.body));
  }

  /** Path part for operation `unloadPlugin()` */
  static readonly UnloadPluginPath = '/api/plugins/{pluginId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `unloadPlugin()` instead.
   *
   * This method doesn't expect any request body.
   */
  unloadPlugin$Response(
    params: UnloadPlugin$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<PluginActionResponse>> {
    const obs = unloadPlugin(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `unloadPlugin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  unloadPlugin(params: UnloadPlugin$Params, context?: HttpContext): Observable<PluginActionResponse> {
    const resp = this.unloadPlugin$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<PluginActionResponse>): PluginActionResponse => r.body));
  }

  /** Path part for operation `debugPlugin()` */
  static readonly DebugPluginPath = '/api/plugins/{pluginId}/debug';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `debugPlugin()` instead.
   *
   * This method doesn't expect any request body.
   */
  debugPlugin$Response(
    params: DebugPlugin$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<PluginActionResponse>> {
    const obs = debugPlugin(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `debugPlugin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  debugPlugin(params: DebugPlugin$Params, context?: HttpContext): Observable<PluginActionResponse> {
    const resp = this.debugPlugin$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<PluginActionResponse>): PluginActionResponse => r.body));
  }

  /** Path part for operation `debugAllPlugins()` */
  static readonly DebugAllPluginsPath = '/api/plugins/debug';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `debugAllPlugins()` instead.
   *
   * This method doesn't expect any request body.
   */
  debugAllPlugins$Response(
    params?: DebugAllPlugins$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<PluginActionResponse>> {
    const obs = debugAllPlugins(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `debugAllPlugins$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  debugAllPlugins(params?: DebugAllPlugins$Params, context?: HttpContext): Observable<PluginActionResponse> {
    const resp = this.debugAllPlugins$Response(params, context);
    return resp.pipe(map((r: StrictHttpResponse<PluginActionResponse>): PluginActionResponse => r.body));
  }
}
