@namespaceId=4fbbbb65-6aaa-46d7-adf3-5b3fb62ddad3
@userExternalId=

### Create a agent config
POST {{apiBaseUrl}}/api/agent-configs
Content-Type: application/json

{
  "namespaceId": "{{namespaceId}}",
  "name": "Agent 1"
}

### List agents by namespace id
GET {{apiBaseUrl}}/api/agent-configs/by-parentId/{{namespaceId}}
Content-Type: application/json


### List agents by user external id
GET {{apiBaseUrl}}/api/agent-configs/available-agents?userExternalId={{userExternalId}}
Content-Type: application/json
