@namespaceExternalId=123
@agentId=2495be79-e5e7-49ce-a1b3-771897f9c44b
@userGroupId=08577023-6fd2-4c1d-bc64-d48317c979f6

### List user groups
GET {{apiBaseUrl}}/api/user-groups?namespaceExternalId={{namespaceExternalId}}
Content-Type: application/json

### Read user groups
GET {{apiBaseUrl}}/api/user-groups/{{userGroupId}}
Content-Type: application/json

### Create a user group
POST {{apiBaseUrl}}/api/user-groups
Content-Type: application/json

{
  "namespaceExternalId": "{{namespaceExternalId}}",
  "name": "User group 1",
  "agentIds": ["{{agentId}}"],
  "userExternalIdsToAdd": ["alan"]
}


### Delete a user group
DELETE {{apiBaseUrl}}/api/user-groups/{{userGroupId}}
