@namespaceExternalId=456
@agentId=cb631ec3-0169-41cf-a4e2-3de4c2eaec5f
@userGroupId=b5a467a8-e355-4a1d-9ac3-9343f3cd4830

### List user groups
GET {{apiBaseUrl}}/api/user-groups?namespaceExternalId={{namespaceExternalId}}
Content-Type: application/json

### Read user groups
GET {{apiBaseUrl}}/api/user-groups/{{userGroupId}}
Content-Type: application/json


### Create a user group
POST {{apiBaseUrl}}/api/user-groups
Content-Type: application/json

{
  "namespaceExternalId": "{{namespaceExternalId}}",
  "name": "User group 3",
  "agentIds": ["{{agentId}}"],
  "userExternalIds": ["alan"]
}
