package io.whozoss.factory.planchange.domain

import java.time.Instant

/**
 * Supporting immutable value types of the plan-change aggregate (Phase 8 governed
 * replanning): the proposed change payloads, the append-only decision events and
 * the validated commands the service orchestrates.
 */

/** Operation of a proposed dependency change between two existing steps. */
enum class DependencyOp(val wireValue: String) {
    ADD("ADD"),
    REMOVE("REMOVE"),
    ;

    companion object {
        /** Parse a caller-supplied op, case-insensitively; `null` when unknown. */
        fun parse(value: String?): DependencyOp? =
            value?.trim()?.uppercase()?.let { normalized -> entries.firstOrNull { it.wireValue == normalized } }
    }
}

/** One proposed dependency edge change between two existing steps. */
data class DependencyChange(
    val op: DependencyOp,
    val fromStepId: String,
    val toStepId: String,
)

/** Operation of a proposed scope change. */
enum class ScopeChangeOp(val wireValue: String) {
    /** Scope expansion — always requires a human governance gate (Rule 3). */
    EXPAND("EXPAND"),

    /** Scope reduction. */
    REDUCE("REDUCE"),

    /** Scope modification that is neither a pure expansion nor a pure reduction. */
    MODIFY("MODIFY"),
    ;

    companion object {
        /** Parse a caller-supplied op, case-insensitively; `null` when unknown. */
        fun parse(value: String?): ScopeChangeOp? =
            value?.trim()?.uppercase()?.let { normalized -> entries.firstOrNull { it.wireValue == normalized } }
    }
}

/** One proposed scope change. */
data class ScopeChange(
    val op: ScopeChangeOp,
    val target: String,
    val detail: String? = null,
)

/**
 * One immutable decision event of the append-only decision log.
 *
 * Decisions are never updated nor deleted; [sequence] is the monotone ordering key
 * generated by the persistence adapter as `MAX(sequence) + 1`.
 */
data class PlanChangeDecision(
    val sequence: Long,
    val status: PlanChangeDecisionStatus,
    val actorId: String,
    val reason: String? = null,
    val idempotencyKey: String? = null,
    val recordedAt: Instant,
)

/** Validated submission payload of a plan-change proposal. */
data class PlanChangeSubmitCommand(
    val workflowId: String,
    val namespaceId: String,
    val expectedRevision: Int,
    val reasonCode: String,
    val summary: String,
    val proposalType: PlanChangeProposalType,
    val affectedStepIds: List<String> = emptyList(),
    val proposedDependencyChanges: List<DependencyChange> = emptyList(),
    val proposedScopeChanges: List<ScopeChange>? = null,
    val evidenceRefs: List<String> = emptyList(),
    val idempotencyKey: String,
)

/** Validated decision payload of a `/decide` call. */
data class PlanChangeDecideCommand(
    val expectedRevision: Int,
    val decision: PlanChangeDecisionStatus,
    val reason: String? = null,
    val idempotencyKey: String? = null,
)
