/**
 * agentos-download.ts
 *
 * Download all 5 AgentOS JARs from GitHub Release assets, verify their
 * SHA-256 checksums, write them atomically to disk, and clean up stale JARs.
 *
 * Layout (mode managé only):
 *   <configDir>/agentos/agentos-service-<version>.jar
 *   <configDir>/agentos/plugins/agentos-bash-plugin-<version>.jar
 *   <configDir>/agentos/plugins/agentos-file-plugin-<version>.jar
 *   <configDir>/agentos/plugins/agentos-mcp-plugin-<version>.jar
 *   <configDir>/agentos/plugins/agentos-tmux-plugin-<version>.jar
 *
 * INVARIANTS:
 *   - Never throws. Every error is caught, logged, and returned as a structured result.
 *   - No side effects at import time.
 *   - No new npm dependencies (uses Node 24 built-in fetch + node:crypto + node:fs).
 *   - No network access unless JARs are absent or at the wrong version.
 */

import * as crypto from 'crypto'
import * as fs from 'fs'
import * as path from 'path'
import { debugLog } from './log'
import { AGENTOS_ARTIFACT_IDS, AgentosArtifactId, expectedJarPath } from './agentos-lifecycle'

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Timeout for each individual HTTP request. */
const FETCH_TIMEOUT_MS = 60_000

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export type DownloadOutcome =
  | 'skipped:all-present' // All JARs already at the expected version
  | 'skipped:dev-version' // getCodayVersion() returned 'dev' — no release to download from
  | 'error:manifest-unavailable' // checksums.sha256 returned non-2xx
  | 'error:manifest-parse' // checksums.sha256 could not be parsed
  | 'error:download-failed' // One or more JARs failed to download/verify/write
  | 'success' // All needed JARs downloaded, verified, written; stale JARs cleaned

export interface DownloadResult {
  outcome: DownloadOutcome
  /** Human-readable description of the outcome. */
  message: string
  /** Number of JARs successfully downloaded. */
  downloaded?: number
  /** Number of stale JARs removed. */
  cleaned?: number
}

// ---------------------------------------------------------------------------
// URL builders
// ---------------------------------------------------------------------------

/**
 * Build the GitHub Release download URL for a versioned JAR asset.
 * Tag pattern confirmed in .github/workflows/release.yml: TAG="release/${VERSION}"
 */
function buildJarUrl(artifactId: string, version: string): string {
  return `https://github.com/whoz-oss/coday/releases/download/release/${version}/${artifactId}-${version}.jar`
}

/**
 * Build the GitHub Release download URL for the checksums manifest.
 */
function buildManifestUrl(version: string): string {
  return `https://github.com/whoz-oss/coday/releases/download/release/${version}/checksums.sha256`
}

// ---------------------------------------------------------------------------
// Manifest parsing
// ---------------------------------------------------------------------------

/**
 * Parse the checksums.sha256 manifest and extract the hash for a given filename.
 *
 * Format (generated by `sha256sum *.jar`):
 *   <64-hex-chars>  <filename>\n
 * (two spaces between hash and filename)
 *
 * Filenames in the manifest are VERSIONED (e.g. "agentos-bash-plugin-0.244.0.jar").
 */
function extractHashFromManifest(manifestText: string, targetFilename: string): string | null {
  for (const line of manifestText.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed) continue
    const spaceIdx = trimmed.indexOf('  ')
    if (spaceIdx === -1) continue
    const hash = trimmed.slice(0, spaceIdx).trim()
    const filename = trimmed.slice(spaceIdx + 2).trim()
    if (filename === targetFilename && hash.length === 64) {
      return hash
    }
  }
  return null
}

// ---------------------------------------------------------------------------
// Checksum
// ---------------------------------------------------------------------------

function sha256hex(data: Buffer): string {
  return crypto.createHash('sha256').update(data).digest('hex')
}

// ---------------------------------------------------------------------------
// Strict cleanup
// ---------------------------------------------------------------------------

/**
 * Remove any JAR in the given directory that is NOT in the allowedFilenames set.
 * Logs each deletion. Never throws.
 */
function cleanDirectory(dir: string, allowedFilenames: Set<string>): number {
  let removed = 0
  try {
    const entries = fs.readdirSync(dir).filter((f) => f.endsWith('.jar') || f.endsWith('.tmp'))
    for (const filename of entries) {
      if (!allowedFilenames.has(filename)) {
        const fullPath = path.join(dir, filename)
        try {
          fs.unlinkSync(fullPath)
          debugLog('AGENTOS', `  [CLEAN] Removed stale file: ${fullPath}`)
          removed++
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err)
          debugLog('AGENTOS', `  [CLEAN] Failed to remove ${fullPath}: ${msg}`)
        }
      }
    }
  } catch {
    // Directory doesn't exist — nothing to clean
  }
  return removed
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

/**
 * Download all missing AgentOS JARs from GitHub Release assets, verify their
 * SHA-256 checksums, write them atomically to disk, then clean up stale JARs.
 *
 * Conditions under which NO network access is attempted:
 *   - All JARs are already present at the expected version
 *   - The resolved version is the sentinel 'dev'
 *
 * If any download fails, the function returns an error outcome immediately
 * (no retry, no partial recovery — next startup will retry).
 *
 * @param configDir       Root config directory (from codayOptions.configDir).
 * @param expectedVersion Version string from getCodayVersion().
 * @param missingArtifacts Artifact IDs that are absent or at the wrong version.
 * @returns A structured DownloadResult describing every step taken.
 */
export async function downloadAgentosJars(
  configDir: string,
  expectedVersion: string,
  missingArtifacts: AgentosArtifactId[]
): Promise<DownloadResult> {
  // --- Guard: skip if all present ---
  if (missingArtifacts.length === 0) {
    debugLog('AGENTOS', '[DOWNLOAD] All JARs already present at the expected version — skipping download')
    return { outcome: 'skipped:all-present', message: 'All JARs already present at the expected version' }
  }

  // --- Guard: skip if version is the 'dev' sentinel ---
  if (expectedVersion === 'dev') {
    debugLog('AGENTOS', "[DOWNLOAD] Version is 'dev' sentinel — no release to download from")
    return { outcome: 'skipped:dev-version', message: "Version is 'dev' sentinel — no release URL available" }
  }

  const agentosDir = path.join(configDir, 'agentos')
  const pluginsDir = path.join(agentosDir, 'plugins')
  const manifestUrl = buildManifestUrl(expectedVersion)

  debugLog(
    'AGENTOS',
    `[DOWNLOAD] Starting download of ${missingArtifacts.length} artifact(s) for version ${expectedVersion}`
  )
  debugLog('AGENTOS', `[DOWNLOAD] Missing: ${missingArtifacts.join(', ')}`)
  debugLog('AGENTOS', `[DOWNLOAD] Manifest URL: ${manifestUrl}`)

  // --- Step 1: Fetch the checksums manifest ONCE for all artifacts ---
  let manifestText: string
  try {
    const controller = new AbortController()
    const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS)
    let manifestRes: Response
    try {
      manifestRes = await fetch(manifestUrl, { signal: controller.signal })
    } finally {
      clearTimeout(timer)
    }

    debugLog('AGENTOS', `[DOWNLOAD] Manifest HTTP ${manifestRes.status}`)

    if (!manifestRes.ok) {
      return {
        outcome: 'error:manifest-unavailable',
        message: `Manifest request failed with HTTP ${manifestRes.status} — cannot verify JAR integrity, aborting download`,
      }
    }
    manifestText = await manifestRes.text()
    debugLog('AGENTOS', `[DOWNLOAD] Manifest fetched (${manifestText.length} chars)`)
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    debugLog('AGENTOS', `[DOWNLOAD] Manifest fetch error: ${msg}`)
    return {
      outcome: 'error:manifest-unavailable',
      message: `Network error fetching manifest: ${msg}`,
    }
  }

  // --- Step 2: Ensure directories exist ---
  try {
    fs.mkdirSync(agentosDir, { recursive: true })
    fs.mkdirSync(pluginsDir, { recursive: true })
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    debugLog('AGENTOS', `[DOWNLOAD] Failed to create directories: ${msg}`)
    return { outcome: 'error:download-failed', message: `Failed to create directories: ${msg}` }
  }

  // --- Step 3: Download each missing artifact ---
  let downloadedCount = 0

  for (const artifactId of missingArtifacts) {
    const jarFilename = `${artifactId}-${expectedVersion}.jar`
    const destPath = expectedJarPath(configDir, artifactId, expectedVersion)
    const jarUrl = buildJarUrl(artifactId, expectedVersion)

    debugLog('AGENTOS', `[DOWNLOAD] Downloading ${jarFilename}...`)
    debugLog('AGENTOS', `[DOWNLOAD]   URL: ${jarUrl}`)

    // Extract expected hash from manifest
    const expectedHash = extractHashFromManifest(manifestText, jarFilename)
    if (!expectedHash) {
      debugLog('AGENTOS', `[DOWNLOAD]   ERROR: No entry for '${jarFilename}' in manifest`)
      return {
        outcome: 'error:manifest-parse',
        message: `Could not find hash for '${jarFilename}' in manifest — aborting`,
      }
    }
    debugLog('AGENTOS', `[DOWNLOAD]   Expected SHA-256: ${expectedHash}`)

    // Fetch the JAR
    let jarBuffer: Buffer
    try {
      const controller = new AbortController()
      const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS)
      let jarRes: Response
      try {
        jarRes = await fetch(jarUrl, { signal: controller.signal })
      } finally {
        clearTimeout(timer)
      }

      debugLog('AGENTOS', `[DOWNLOAD]   JAR HTTP ${jarRes.status}`)

      if (!jarRes.ok) {
        return {
          outcome: 'error:download-failed',
          message: `JAR request for '${jarFilename}' failed with HTTP ${jarRes.status} — aborting`,
        }
      }

      const arrayBuffer = await jarRes.arrayBuffer()
      jarBuffer = Buffer.from(arrayBuffer)
      debugLog('AGENTOS', `[DOWNLOAD]   Received ${jarBuffer.length} bytes`)
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      debugLog('AGENTOS', `[DOWNLOAD]   Network error fetching ${jarFilename}: ${msg}`)
      return {
        outcome: 'error:download-failed',
        message: `Network error fetching '${jarFilename}': ${msg} — aborting`,
      }
    }

    // Verify checksum
    const downloadedHash = sha256hex(jarBuffer)
    debugLog('AGENTOS', `[DOWNLOAD]   Computed  SHA-256: ${downloadedHash}`)
    if (downloadedHash !== expectedHash) {
      debugLog('AGENTOS', `[DOWNLOAD]   CHECKSUM MISMATCH — discarding downloaded bytes`)
      return {
        outcome: 'error:download-failed',
        message: `Checksum mismatch for '${jarFilename}' — downloaded bytes discarded, aborting`,
      }
    }
    debugLog('AGENTOS', `[DOWNLOAD]   Checksum OK`)

    // Atomic write: temp file then rename
    const tmpPath = `${destPath}.tmp`
    try {
      fs.writeFileSync(tmpPath, jarBuffer)
      fs.renameSync(tmpPath, destPath)
      debugLog('AGENTOS', `[DOWNLOAD]   Written to ${destPath} (${jarBuffer.length} bytes)`)
      downloadedCount++
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      debugLog('AGENTOS', `[DOWNLOAD]   Write error for ${jarFilename}: ${msg}`)
      // Best-effort cleanup of the temp file
      try {
        fs.unlinkSync(tmpPath)
      } catch {
        /* ignore */
      }
      return {
        outcome: 'error:download-failed',
        message: `Failed to write '${jarFilename}' to disk: ${msg} — aborting`,
      }
    }
  }

  // --- Step 4: Strict cleanup — remove any JAR that should not be there ---
  // Root dir: only agentos-service-<version>.jar is allowed
  const allowedRoot = new Set([`agentos-service-${expectedVersion}.jar`])
  // Plugins dir: only the 4 plugin JARs at the expected version are allowed
  const allowedPlugins = new Set(
    AGENTOS_ARTIFACT_IDS.filter((id) => id !== 'agentos-service').map((id) => `${id}-${expectedVersion}.jar`)
  )

  debugLog('AGENTOS', '[DOWNLOAD] Running strict cleanup...')
  const cleanedRoot = cleanDirectory(agentosDir, allowedRoot)
  const cleanedPlugins = cleanDirectory(pluginsDir, allowedPlugins)
  const totalCleaned = cleanedRoot + cleanedPlugins

  if (totalCleaned > 0) {
    debugLog('AGENTOS', `[DOWNLOAD] Cleanup complete: removed ${totalCleaned} stale file(s)`)
  } else {
    debugLog('AGENTOS', '[DOWNLOAD] Cleanup complete: no stale files found')
  }

  return {
    outcome: 'success',
    message: `Downloaded ${downloadedCount} JAR(s), cleaned ${totalCleaned} stale file(s)`,
    downloaded: downloadedCount,
    cleaned: totalCleaned,
  }
}
