/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Actor } from '../models/actor'
import { CaseEvent } from '../models/case-event'
export type AnswerEvent = CaseEvent & {
  questionId?: string
  actor?: Actor
  answer?: string
}
