/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CaseEvent } from '../models/case-event';
export type CaseStatusEvent = CaseEvent & {
'status'?: 'PENDING' | 'RUNNING' | 'STOPPING' | 'ERROR' | 'STOPPED';
};

