/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntityMetadata } from '../models/entity-metadata'
export interface CaseEvent {
  caseId: string
  id: string
  metadata: EntityMetadata
  projectId: string
  timestamp: string
  type:
    | 'STATUS'
    | 'AGENT_SELECTED'
    | 'MESSAGE'
    | 'TOOL_REQUEST'
    | 'TOOL_RESPONSE'
    | 'THINKING'
    | 'AGENT_FINISHED'
    | 'AGENT_RUNNING'
    | 'WARN'
    | 'ERROR'
    | 'QUESTION'
    | 'ANSWER'
    | 'INTENTION_GENERATED'
    | 'TOOL_SELECTED'
    | 'TEXT_CHUNK'
}
