/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntityMetadata } from '../models/entity-metadata';
export interface CaseModel {
  id: string;
  metadata: EntityMetadata;
  projectId: string;
  status: 'PENDING' | 'RUNNING' | 'STOPPING' | 'ERROR' | 'STOPPED';
}
