package io.whozoss.agentos.sdk.usage

/**
 * Aggregated LLM token usage for a case or a single agent turn.
 *
 * ## Token count semantics — normalised across providers
 *
 * All token counts use a **provider-normalised** convention so that aggregations
 * across providers produce meaningful totals:
 *
 * - [inputTokens] — tokens billed at the **full input rate** (prompt tokens that
 *   were NOT served from cache). Computed as:
 *   - **Anthropic**: `inputTokens` reported by the API (already excludes cache tokens).
 *   - **OpenAI / vLLM**: `promptTokens − cachedTokens` (OpenAI includes cached tokens
 *     in `promptTokens`; subtracting them avoids double-counting with [cacheReadTokens]).
 *   Floored at 0 to absorb any provider-side reporting inconsistency.
 *
 * - [outputTokens] — tokens generated by the model (same meaning on all providers).
 *
 * - [cacheReadTokens] — tokens served from the provider's prompt cache:
 *   - **Anthropic**: `cacheReadInputTokens`.
 *   - **OpenAI**: `PromptTokensDetails.cachedTokens`.
 *   - 0 when the provider does not report cache details or the model was invoked
 *     without caching.
 *
 * - [cacheWriteTokens] — tokens written into the provider's prompt cache:
 *   - **Anthropic**: `cacheCreationInputTokens`.
 *   - **OpenAI**: always 0 (OpenAI does not expose a cache-write token count).
 *
 * - [totalTokens] — the **raw** provider-reported total (included for reconciliation
 *   with provider dashboards). May differ from `inputTokens + outputTokens +
 *   cacheReadTokens + cacheWriteTokens` because providers compute it differently.
 *
 * - [estimatedCostUsd] — cost in USD estimated from the above counts and the
 *   per-million-token rates configured on [io.whozoss.agentos.sdk.aiProvider.AiModel].
 *   `null` when no pricing is configured for the model (not the same as zero cost).
 *
 * This data class is part of the public SDK surface so plugins can read usage figures
 * without depending on Spring AI classes.
 */
data class LlmUsage(
    val inputTokens: Long = 0L,
    val outputTokens: Long = 0L,
    val cacheReadTokens: Long = 0L,
    val cacheWriteTokens: Long = 0L,
    val totalTokens: Long = 0L,
    val estimatedCostUsd: Double? = null,
) {
    /**
     * Returns a new [LlmUsage] with all token counts and cost summed with [other].
     *
     * Cost is summed when both sides are non-null; stays null when either side is null
     * (one unconfigured model taints the total — null means "unknown", not zero).
     */
    operator fun plus(other: LlmUsage): LlmUsage =
        LlmUsage(
            inputTokens = inputTokens + other.inputTokens,
            outputTokens = outputTokens + other.outputTokens,
            cacheReadTokens = cacheReadTokens + other.cacheReadTokens,
            cacheWriteTokens = cacheWriteTokens + other.cacheWriteTokens,
            totalTokens = totalTokens + other.totalTokens,
            estimatedCostUsd =
                when {
                    estimatedCostUsd != null && other.estimatedCostUsd != null -> estimatedCostUsd + other.estimatedCostUsd
                    else -> null
                },
        )

    companion object {
        val ZERO = LlmUsage()
    }
}
