/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PluginActionResponse } from '../../models/plugin-action-response';

export interface UnloadPlugin$Params {
  pluginId: string;
}

export function unloadPlugin(http: HttpClient, rootUrl: string, params: UnloadPlugin$Params, context?: HttpContext): Observable<StrictHttpResponse<PluginActionResponse>> {
  const rb = new RequestBuilder(rootUrl, unloadPlugin.PATH, 'delete');
  if (params) {
    rb.path('pluginId', params.pluginId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PluginActionResponse>;
    })
  );
}

unloadPlugin.PATH = '/api/plugins/{pluginId}';
