/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { RequestBuilder } from '../../request-builder'

import { CaseResponse } from '../../models/case-response'

export interface GetCase$Params {
  caseId: string
}

export function getCase(
  http: HttpClient,
  rootUrl: string,
  params: GetCase$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<CaseResponse>> {
  const rb = new RequestBuilder(rootUrl, getCase.PATH, 'get')
  if (params) {
    rb.path('caseId', params.caseId, {})
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CaseResponse>
    })
  )
}

getCase.PATH = '/api/cases/{caseId}'
