/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { RequestBuilder } from '../../request-builder'

import { CaseModel } from '../../models/case-model'

export interface ListByParent$Params {
  parentId: string
  ids: Array<string>
}

export function listByParent(
  http: HttpClient,
  rootUrl: string,
  params: ListByParent$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<Array<CaseModel>>> {
  const rb = new RequestBuilder(rootUrl, listByParent.PATH, 'get')
  if (params) {
    rb.query('parentId', params.parentId, {})
    rb.query('ids', params.ids, {})
  }

  return http.request(rb.build({ responseType: 'blob', accept: '*/*', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CaseModel>>
    })
  )
}

listByParent.PATH = '/api/cases'
