package io.whozoss.factory.lease.persistence

import io.whozoss.factory.lease.domain.LeaseStatus
import io.whozoss.factory.lease.domain.WorkUnitLease
import org.springframework.data.neo4j.core.schema.Id
import org.springframework.data.neo4j.core.schema.Node
import java.time.Instant

/**
 * Spring Data Neo4j projection of the [WorkUnitLease] aggregate.
 *
 * Replaces the `work_unit_leases` PostgreSQL row. The node [id] is the composite
 * business key `(organizationId, workstreamId, workUnitId, leaseId)` encoded as
 * a single string. The monotone [fencingToken] is generated by the adapter and
 * stored as a property.
 */
@Node("WorkUnitLease")
data class LeaseNode(
    @Id
    val id: String,
    val organizationId: String,
    val workstreamId: String,
    val workUnitId: String,
    val leaseId: String,
    val workerId: String,
    val environmentId: String? = null,
    val status: String,
    val fencingToken: Long,
    val acquiredAt: Instant? = null,
    val leaseExpiresAt: Instant? = null,
    val heartbeatAt: Instant? = null,
    val releasedAt: Instant? = null,
    val expiryReason: String? = null,
    val createdAt: Instant? = null,
) {
    fun status(): LeaseStatus = LeaseStatus.fromDbValue(status)

    companion object {
        fun compositeId(organizationId: String, workstreamId: String, workUnitId: String, leaseId: String): String =
            "$organizationId|$workstreamId|$workUnitId|$leaseId"
    }
}

/** Maps a graph node back to the [WorkUnitLease] domain aggregate. */
fun LeaseNode.toDomain(): WorkUnitLease = WorkUnitLease(
    organizationId = organizationId,
    workstreamId = workstreamId,
    workUnitId = workUnitId,
    leaseId = leaseId,
    workerId = workerId,
    environmentId = environmentId,
    status = status(),
    fencingToken = fencingToken,
    acquiredAt = acquiredAt,
    leaseExpiresAt = leaseExpiresAt,
    heartbeatAt = heartbeatAt,
    releasedAt = releasedAt,
    expiryReason = expiryReason,
    createdAt = createdAt,
)
