/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Namespace } from '../../models/namespace';

export interface ListByParent$Params {
  parentId: any;
}

export function listByParent(http: HttpClient, rootUrl: string, params: ListByParent$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Namespace>>> {
  const rb = new RequestBuilder(rootUrl, listByParent.PATH, 'get');
  if (params) {
    rb.path('parentId', params.parentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Namespace>>;
    })
  );
}

listByParent.PATH = '/api/namespaces/by-parentId/{parentId}';
