name: Build Coday on push to master

on:
  push:
    branches:
      - master

env:
  NX_MAX_WORKERS: 4

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build app
        run: npx nx run web:build --parallel=$NX_MAX_WORKERS
